[target.aarch64-unknown-linux-musl]
linker = "aarch64-linux-musl-gcc"
rustflags = ["-C", "target-feature=-crt-static", "linker=aarch64-linux-musl-gcc"] 

[target.x86_64-unknown-linux-musl]
linker = "clang"
rustflags=["-C", "target-feature=-crt-static"]